baseURL = "https://blog.peritofabricioribeiro.com.br/"
languageCode = "pt-BR"
defaultContentLanguage = "pt-br"
title = "Fabricio Ribeiro — Perito Judicial"
theme = "PaperMod"

[params]
  author = "Fabricio do Nascimento Ribeiro"
  description = "Blog sobre computação forense, impugnação de laudo pericial e assinatura eletrônica"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  disableSpecial1stPost = false
  displayFullLangName = false
  ShowFullTextinRSS = false
   env = "production"
  DateFormat = "2 January 2006"   # ou "02/01/2006"
  ShowLastMod = true
  ShowWordCount = true
  ShowCanonical = true

  [params.giscus]
    repo = "seu-usuario/seu-repo"
    repoId = "R_xxxxx"
    category = "General"
    categoryId = "DIC_xxxxx"
    mapping = "pathname"
    theme = "dark_dimmed"
    lang = "pt"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]

 
  [params.homeInfoParams]
    Title = "Blog do Fabricio Ribeiro"
    Content = "Computação forense, impugnação de laudo pericial e assinatura eletrônica."

    [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/fabricio-ribeiro-perito/"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/perito_fabriciorib_sc/"
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Artigos"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about/"
    weight = 20

    [[menu.main]]
  identifier = "categorias"
  name = "Categorias"
  url = "/categories/"
  weight = 15

  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 16

[[menu.main]]
  identifier = "contato"
  name = "Contato"
  url = "/contato/"
  weight = 30


 [params.assets]
    favicon = "/favicon.ico"

 